apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiftsync-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiftsync
  template:
    metadata:
      labels:
        app: shiftsync
    spec:
      containers:
      - name: shiftsync
        image: shiftsync-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000