apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: s224719679/admin-service:v3
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value : mongodb://mongo-service:27017/shiftsync