apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: s224719679/frontend-service:v4
          ports:
            - containerPort: 3003
          env:
            - name: AUTH_API_URL
              value: "http://335.244.91.242:3000"
            - name: ADMIN_API_URL
              value: "http://35.189.45.141:3000"