apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiftsync-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiftsync
  template:
    metadata:
      labels:
        app: shiftsync
    spec:
      containers:
        - name: shiftsync
          image: s224719679/projectshiftsync:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-pass
            - name: MONGO_URL
              value: mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo-service:27017/shiftsync?authSource=admin